print('hello')
print('keril')
print('vova pidor')
print('i huesos')
print('zaebal uzhe')
print('pol tretyego, blyat, a ya s etim ebus !!!1111!111!1111!!1')
print('tritiy den uzhe nahui')
print('zaebsya suka')
